# Validación cruzada
# Cross Validation

In [3]:
# Importar las librerías
import pandas as pd
import numpy as np

In [4]:
# Importar el dataset vinos
df = pd.read_excel('Vinos.xlsx', index_col = 'num')

In [7]:
# Ver los 5 primeros registros
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,color
num,,,,,,,,,,,,,
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red

In [6]:
# Convertir color en categoría
df['color']= df['color'].astype('category')

In [9]:
# Remplazar color por el código de su categoría
df['color'] = df['color'].cat.codes
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,color
num,,,,,,,,,,,,,
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,0
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0

In [10]:
# Crear función que intercambia el orden de dos columnas (no cambia los títulos)
def swap_columns(df, c1, c2):
    df['temp'] = df[c1]
    df[c1] = df[c2]
    df[c2] = df['temp']
    df.drop(columns=['temp'], inplace=True)

In [11]:
# Intercambiar las columnas 'quality' y 'color'
swap_columns(df,'quality','color')

In [13]:
# Mostrar los primeros 5 registros
df.head(5)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,color
num,,,,,,,,,,,,,
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,0,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,0,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,0,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,0,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,0,5

In [16]:
# Cambiar también el nombre de las columnas
lista_col = list(df)
lista_col[-1],lista_col[-2] = lista_col[-2],lista_col[-1]
df.columns = lista_col

In [17]:
# Mostrar los primeros 5 registros
df.head(5)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,color,quality
num,,,,,,,,,,,,,
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,0,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,0,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,0,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,0,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,0,5

## Validación cruzada

In [21]:
# Importar las librerías
from sklearn.svm import SVC #Este el se estimador que usaremos 
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, recall_score

In [22]:
# Features del dataframe
X = df[df.columns[:-1]]
# Clases del dataframe
Y = df['quality']

In [26]:
# Instanciar el modelo
svm = SVC()
# Crear la validación cruzada. 1) Midiendo la exactitud
# Para el scoring
# https://scikit-learn.org/stable/modules/model_evaluation.html

scores1 = cross_val_score(svm,X,Y,cv=10,scoring= 'accuracy')

C:\Users\Steven\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:667: UserWarning: The least populated class in y has only 5 members, which is less than n_splits=10.
  % (min_groups, self.n_splits)), UserWarning)

In [33]:
# Imprimir la lista de exactitud y su media
print("Scores_1 = ",scores1)
print('Media de scores1 = ',scores1.mean())

Scores_1 =  [0.28461538 0.43692308 0.32307692 0.42615385 0.46769231 0.41846154
 0.43846154 0.4422188  0.4375963  0.4375963 ]
Media de scores1 =  0.411279601754178

In [34]:
# Crear la validación cruzada. 1) Midiendo la sensibilidad ponderada
scores2 = cross_val_score(svm,X,Y,cv=10,scoring='')

C:\Users\Steven\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:667: UserWarning: The least populated class in y has only 5 members, which is less than n_splits=10.
  % (min_groups, self.n_splits)), UserWarning)

In [ ]:
# Imprimir la lista de sensibilidad y su media
print("Scores_2 = ",scores2)
print('Media de scores2 = ',scores2.mean())

In [ ]:
# Crear la validación cruzada. 1) Midiendo la sensibilidad promedio
scores3 = cross_val_score(svm,X,Y,cv=10,scoring='recall_macro')